Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
    Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false